{% set name = "empy" %}
{% set version = "4.0.1" %}
{% set sha256 = "1e7b4c8c4b5f28ab1957c5c303ae22a176494d13dde07a7e098764c0d342b618" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.alcyone.com/software/empy/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - em

about:
  home: http://www.alcyone.com/software/empy/
  license: LGPL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'A powerful and robust templating system for Python.'
  dev_url: http://www.alcyone.com/software/empy/

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
